#!/usr/bin/env node
/**
 * Bundle docs/wiki/*.md into wiki-bundle.js for the in-app documentation viewer.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..', '..', '..');
const wikiDir = path.join(root, 'docs', 'wiki');
const outFile = path.join(__dirname, '..', 'wiki-bundle.js');

const SKIP = new Set(['README.md', '_Sidebar.md', '_Footer.md']);

const NAV = [
  {
    id: 'start',
    label: 'Start here',
    pages: [
      'Home',
      'Installation',
      'Quick-Start-Checklist',
      'Dashboard-Overview',
      'Dashboard-Tabs',
      'Understanding-Data-Sources',
      'Using-Spark-with-Watchtower',
      'Live-Charts',
    ],
  },
  {
    id: 'ops',
    label: 'Day-to-day',
    pages: [
      'Commands',
      'Configuration',
      'Security-and-Access',
      'Hosting-Panels',
      'Reading-Metrics-on-Hosted-Servers',
      'Health-Reports',
      'Backups',
      'Scheduled-Reports',
    ],
  },
  {
    id: 'dr',
    label: 'When things go wrong',
    pages: ['Disaster-Recovery', 'DR-CLI-Reference', 'DR-Viewer'],
  },
  {
    id: 'ref',
    label: 'Reference',
    pages: [
      'HTTP-API',
      'On-disk-Files',
      'Troubleshooting',
      'Downloads-and-Releases',
      'Roadmap',
      'Changelog',
    ],
  },
];

function slugFromFile(name) {
  return name.replace(/\.md$/i, '');
}

function titleFromMarkdown(md) {
  const m = md.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : 'Untitled';
}

function build() {
  if (!fs.existsSync(wikiDir)) {
    throw new Error(`Wiki source not found: ${wikiDir}`);
  }

  const pages = {};
  for (const name of fs.readdirSync(wikiDir)) {
    if (!name.endsWith('.md') || SKIP.has(name)) continue;
    const slug = slugFromFile(name);
    const md = fs.readFileSync(path.join(wikiDir, name), 'utf8');
    pages[slug] = {
      slug,
      title: titleFromMarkdown(md),
      markdown: md,
    };
  }

  const nav = NAV.map((cat) => ({
    ...cat,
    pages: cat.pages.filter((slug) => pages[slug]).map((slug) => ({
      slug,
      title: pages[slug].title,
    })),
  })).filter((cat) => cat.pages.length > 0);

  const payload = { version: 1, nav, pages };
  const js = `/* Auto-generated by scripts/build-wiki.mjs — do not edit */\nwindow.WATCHTOWER_WIKI = ${JSON.stringify(payload)};\n`;
  fs.writeFileSync(outFile, js, 'utf8');
  console.log(`Built ${outFile} (${Object.keys(pages).length} pages, ${fs.statSync(outFile).size} bytes)`);
}

build();
