package dev.mcstatus.watchtower.core.report;

import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import com.google.gson.JsonObject;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.time.format.DateTimeFormatter;
import java.util.zip.ZipOutputStream;

/**
 * Packages a minimal support zip: latest brief, facts, manifest, and README only.
 */
public final class SupportBundlePackager {

    public static final int BUNDLE_VERSION = 1;
    private static final Gson GSON = new GsonBuilder().setPrettyPrinting().create();

    private SupportBundlePackager() {
    }

    public record BundleResult(Path zipPath, long sizeBytes) {
    }

    public static BundleResult packageSupportBundle(Path outDir, Path factsPath, Path briefPath) throws IOException {
        Files.createDirectories(outDir);
        String timestamp = ZonedDateTime.now(ZoneId.systemDefault())
                .format(DateTimeFormatter.ofPattern("yyyy-MM-dd_HH-mm-ss"));
        Path zipPath = outDir.resolve("watchtower-support-" + timestamp + ".zip");

        String factsName = factsPath != null && Files.isRegularFile(factsPath)
                ? factsPath.getFileName().toString()
                : null;
        String briefName = briefPath != null && Files.isRegularFile(briefPath)
                ? briefPath.getFileName().toString()
                : null;

        JsonObject manifest = buildManifest(factsName, briefName);

        try (ZipOutputStream zos = new ZipOutputStream(Files.newOutputStream(zipPath))) {
            ForensicsZipUtil.addTextEntry(zos, "manifest.json", GSON.toJson(manifest));
            if (factsPath != null && Files.isRegularFile(factsPath)) {
                ForensicsZipUtil.addFileEntry(zos, factsName, factsPath);
            }
            if (briefPath != null && Files.isRegularFile(briefPath)) {
                ForensicsZipUtil.addFileEntry(zos, briefName, briefPath);
            }
            ForensicsZipUtil.addTextEntry(zos, "README.txt", readmeText());
        }

        return new BundleResult(zipPath, Files.size(zipPath));
    }

    private static JsonObject buildManifest(String factsName, String briefName) {
        JsonObject manifest = new JsonObject();
        manifest.addProperty("bundle_version", BUNDLE_VERSION);
        manifest.addProperty("report_mode", "support");
        manifest.addProperty("generated_at", ZonedDateTime.now(ZoneId.systemDefault()).toString());
        if (factsName != null) {
            manifest.addProperty("facts", factsName);
        }
        if (briefName != null) {
            manifest.addProperty("brief", briefName);
        }
        return manifest;
    }

    private static String readmeText() {
        return """
                Watchtower support bundle
                =========================
                Upload this zip when asking for help — it contains the latest brief and facts only.

                Generated by: Watchtower dashboard / support bundle API
                """;
    }
}
