#!/usr/bin/env node
/**
 * Bundle docs/wiki/*.md into src/wiki/content.js for the in-app documentation viewer.
 */
import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const root = path.join(__dirname, '..', '..', '..');
const wikiDir = path.join(root, 'docs', 'wiki');
const esModuleOut = path.join(__dirname, '..', 'src', 'wiki', 'content.js');
const legacyOut = path.join(__dirname, '..', 'wiki-bundle.js');

const SKIP = new Set(['README.md', '_Sidebar.md', '_Footer.md']);

const NAV = [
  {
    id: 'start',
    label: 'Start here',
    pages: [
      'Home',
      'Installation',
      'Quick-Start-Checklist',
      'Understanding-Data-Sources',
      'Dashboard-Tabs',
      'Dashboard-Overview',
      'Live-Charts',
    ],
  },
  {
    id: 'use',
    label: 'Use the dashboard',
    pages: [
      'Insights',
      'Session',
      'Startup',
      'Issues',
      'Crashes',
      'Logs',
      'Using-Spark-with-Watchtower',
      'Mods',
      'Backups',
      'Activity',
      'Sources',
    ],
  },
  {
    id: 'wrong',
    label: 'When things go wrong',
    pages: [
      'Troubleshooting',
      'Disaster-Recovery',
      'DR-CLI-Reference',
      'DR-Viewer',
    ],
  },
  {
    id: 'ref',
    label: 'Reference',
    pages: [
      'Configuration',
      'Security-and-Access',
      'Commands',
      'Health-Reports',
      'Hosting-Panels',
      'Reading-Metrics-on-Hosted-Servers',
      'Crash-Rule-Packs',
      'On-disk-Files',
      'HTTP-API',
      'Downloads-and-Releases',
      'Roadmap',
      'Changelog',
    ],
  },
];

function slugFromFile(name) {
  return name.replace(/\.md$/i, '');
}

function titleFromMarkdown(md) {
  const cleaned = String(md ?? '').replace(/^\uFEFF/, '');
  const m = cleaned.match(/^#\s+(.+)$/m);
  return m ? m[1].trim() : 'Untitled';
}

function build() {
  if (!fs.existsSync(wikiDir)) {
    throw new Error(`Wiki source not found: ${wikiDir}`);
  }

  const pages = {};
  for (const name of fs.readdirSync(wikiDir)) {
    if (!name.endsWith('.md') || SKIP.has(name)) continue;
    const slug = slugFromFile(name);
    const md = fs
      .readFileSync(path.join(wikiDir, name), 'utf8')
      .replace(/^\uFEFF/, '')
      .replace(/\r\n/g, '\n')
      .replace(/\r/g, '\n');
    pages[slug] = {
      slug,
      title: titleFromMarkdown(md),
      markdown: md,
    };
  }

  const nav = NAV.map((cat) => ({
    ...cat,
    pages: cat.pages.filter((slug) => pages[slug]).map((slug) => ({
      slug,
      title: pages[slug].title,
    })),
  })).filter((cat) => cat.pages.length > 0);

  const payload = { version: 1, nav, pages };

  const esm = `/* Auto-generated by scripts/build-wiki.mjs — do not edit */\nexport const WIKI = ${JSON.stringify(payload, null, 2)};\n`;
  fs.mkdirSync(path.dirname(esModuleOut), { recursive: true });
  writeFileWithRetry(esModuleOut, esm);
  console.log(`Built ${esModuleOut} (ES module, ${Object.keys(pages).length} pages, ${fs.statSync(esModuleOut).size} bytes)`);

  if (fs.existsSync(legacyOut)) {
    fs.unlinkSync(legacyOut);
    console.log(`Removed legacy ${legacyOut}`);
  }
}

/** Windows/AV/IDE watchers sometimes lock content.js mid-write — temp + rename with retries. */
function writeFileWithRetry(target, contents, attempts = 8) {
  const dir = path.dirname(target);
  const tmp = path.join(dir, `.${path.basename(target)}.tmp-${process.pid}`);
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      fs.writeFileSync(tmp, contents, 'utf8');
      try {
        fs.renameSync(tmp, target);
      } catch (renameErr) {
        // replaceFile fails on Windows when target is open — fall back to overwrite
        fs.copyFileSync(tmp, target);
        fs.unlinkSync(tmp);
      }
      return;
    } catch (err) {
      lastErr = err;
      try {
        if (fs.existsSync(tmp)) fs.unlinkSync(tmp);
      } catch {
        // ignore cleanup failures
      }
      const delayMs = 50 * (i + 1) * (i + 1);
      Atomics.wait(new Int32Array(new SharedArrayBuffer(4)), 0, 0, delayMs);
    }
  }
  throw lastErr;
}

build();
