import json
import pathlib
import re

root = pathlib.Path(r"D:/mc-status/docs/wiki")
out = pathlib.Path(r"D:/mc-status/web/dashboard/src/wiki/content.js")

SKIP = {"README.md", "_Sidebar.md", "_Footer.md"}

NAV = [
    {
        "id": "start",
        "label": "Start here",
        "pages": [
            "Home",
            "Installation",
            "Quick-Start-Checklist",
            "Dashboard-Overview",
            "Dashboard-Tabs",
            "Understanding-Data-Sources",
            "Using-Spark-with-Watchtower",
            "Live-Charts",
        ],
    },
    {
        "id": "ops",
        "label": "Day-to-day",
        "pages": [
            "Commands",
            "Configuration",
            "Security-and-Access",
            "Hosting-Panels",
            "Reading-Metrics-on-Hosted-Servers",
            "Health-Reports",
            "Backups",
            "Scheduled-Reports",
        ],
    },
    {
        "id": "dr",
        "label": "When things go wrong",
        "pages": ["Disaster-Recovery", "DR-CLI-Reference", "DR-Viewer"],
    },
    {
        "id": "ref",
        "label": "Reference",
        "pages": [
            "HTTP-API",
            "On-disk-Files",
            "Troubleshooting",
            "Downloads-and-Releases",
            "Roadmap",
            "Changelog",
        ],
    },
]

pages = {}
for p in sorted(root.glob("*.md")):
    if p.name in SKIP:
        continue
    slug = p.stem
    md = p.read_text(encoding="utf-8")
    title = slug.replace("-", " ")
    m = re.search(r"^#\s+(.+)$", md, re.M)
    if m:
        title = m.group(1).strip()
    pages[slug] = {"slug": slug, "title": title, "markdown": md}

nav_out = []
for cat in NAV:
    cat_pages = []
    for slug in cat["pages"]:
        if slug in pages:
            cat_pages.append({"slug": slug, "title": pages[slug]["title"]})
    if cat_pages:
        nav_out.append({"id": cat["id"], "label": cat["label"], "pages": cat_pages})

payload = {"version": 1, "nav": nav_out, "pages": pages}
body = (
    "/* Auto-generated by scripts/build-wiki.mjs — do not edit */\n"
    "export const WIKI = "
    + json.dumps(payload, ensure_ascii=False, indent=2)
    + ";\n"
)
tmp = out.with_suffix(".js.tmp")
tmp.write_text(body, encoding="utf-8")
tmp.replace(out)
print(f"Built {out} ({len(pages)} pages)")
